name: Deploy

# 동작 조건 설정 : Build가 성공되고 pr이 merged 되었을 때 동작한다.
on:
  pull_request:
    branches:
      - main

  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

permissions:
  contents: read

jobs:
  # 위 과정에서 푸시한 이미지를 ec2에서 풀받아서 실행시키는 과정
  run-docker-image-on-ec2:
    if: github.event.pull_request.merged == true
    # build (위)과정이 완료되어야 실행됩니다.
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      # 최신 이미지를 풀받습니다
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/forgrad-app

      # 기존의 컨테이너를 중지시킵니다
      - name: docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      # 최신 이미지를 컨테이너화하여 실행시킵니다
      - name: docker run new container
        run: sudo docker run --name forgrad-app --rm -d -p 8080:8080 -e TZ=Asia/Seoul -v /home/ubuntu/logs:/log ${{ secrets.DOCKERHUB_USERNAME }}/forgrad-app

      # 미사용 이미지를 정리합니다
      - name: delete old docker image
        run: sudo docker system prune -f